backend/covid_report/polling/urls.py
from django.urls import path

from backend.covid_report.polling import views
from backend.covid_report.polling.api.views import DatapointUpdateApiView, DatapointsViewSet
from backend.covid_report.polling.views import ExportView
from backend.covid_report.polling.views import MetricHistoryView
from backend.covid_report.polling.views import ReporterIndexView
from backend.covid_report.polling.views import ReporterRedirectView


app_name = "polling"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("pending/", ReporterRedirectView.as_view(), name="pending"),
    path("<slug:org_slug>/pending/", ReporterIndexView.as_view(), name="pending_for_org"),
    path("<slug:org_slug>/history/<int:pk>/", MetricHistoryView.as_view(), name="metric-history"),

    path("export/", ExportView.as_view(), name="export"),
    path(
        "api/submit/<int:pk>", DatapointUpdateApiView.as_view(), name="json-submit"
    ),
    path(
        "api/datapoints/", DatapointsViewSet.as_view({'get': 'list'}), name="datapoints"
    ),
    path(
        "history/", views.SubmittedMetricListView.as_view(), name="submitted-metric-list",
    ),
]

urls.py
import aldryn_addons.urls
from aldryn_django.utils import i18n_patterns
from django.conf import settings
from django.urls import include, path
from django.views.generic import RedirectView
from djangocms_helpers.sentry_500_error_handler.views import collect_500_error_user_feedback_view

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="polling:homepage")),
] + aldryn_addons.urls.patterns() + i18n_patterns(
    path("", RedirectView.as_view(pattern_name="polling:homepage")),
    path("reports/", include("backend.covid_report.polling.urls")),
    path("accounts/", include("allauth.urls")),
    path("accounts/", include("backend.auth.urls", namespace="backend_auth")),
    path("hijack/", include('hijack.urls', namespace='hijack')),
    *aldryn_addons.urls.i18n_patterns(),  # MUST be the last entry!
)


if not settings.DEBUG:
    handler500 = collect_500_error_user_feedback_view
    handler404 = 'backend.http_errors.views.handler404'

backend/covid_report/polling/admin/forms.py
from datetime import datetime

from django import forms
from django.utils.translation import pgettext

from backend.auth.models import User


class DatapointAdminForm(forms.ModelForm):
    user: User

    def clean(self):
        if not self.instance.is_optional and self.is_value_field_is_empty():
            raise forms.ValidationError(pgettext(
                "admin__datapoint", "The value is required for non optional questions."
            ))
        return super().clean()

    def save(self, commit=True):
        super().save(commit)
        if self.user.is_reviewer:
            self.instance.submitting_user = self.user
            self.instance.submission_datetime = datetime.now()
            self.instance.save()
        return self.instance

    def is_value_field_is_empty(self):
        value_fields = ["status", "text", "numeric"]
        for field in value_fields:
            value = self.cleaned_data.get(f"{field}_value", None)
            if value is not None and value != "":
                return False
        return True

backend/covid_report/polling/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import gettext_lazy as _

from . import models


class FileImportForm(forms.Form):
    file = forms.FileField()


class MetricDisablingForm(forms.Form):
    days_to_keep = forms.IntegerField(
        initial=3, min_value=0, max_value=settings.TIMESLOTS_GENERATION_PERIOD.days,
        help_text=_(
            "By default the disabled question will be demanding entries from the reporters"
            "for the next %(days)s days. You can reduce it here." % {'days': settings.TIMESLOTS_GENERATION_PERIOD.days}
        ),
        label=_("Keep existing empty questions for (days)"),
    )


class BaseDatapointForm(forms.ModelForm):
    def save(self, commit: bool = True) -> models.Datapoint:
        metric_type = self.instance.timeslot.metric.metric_type
        if metric_type == models.MetricType.NUMERIC.value:
            self.instance.numeric_value = self.cleaned_data["value"]
            self.instance.comment = self.cleaned_data["comment"].strip()
        elif metric_type == models.MetricType.STATUS.value:
            self.instance.status_value = self.cleaned_data["value"]
            self.instance.comment = self.cleaned_data["comment"].strip()
        else:
            self.instance.text_value = self.cleaned_data["value"]

        self.instance.save()
        return self.instance

    class Meta:
        model = models.Datapoint
        fields = ()


class ExportForm(forms.Form):
    format = forms.ChoiceField(label=_("Format"), choices=(), required=False)

    def __init__(self, formats, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["format"].choices = [
            (f().get_format().title, f().get_title()) for f in formats
        ]

    def clean_format(self):
        file_format = self.cleaned_data["format"]
        if not file_format:
            return 0
        else:
            for i, f in enumerate(self.fields["format"].choices):
                if f[0] == file_format:
                    return i
            else:
                raise forms.ValidationError(f"Invalid format: {file_format}")

    def clean(self):
        data = super().clean()
        try:
            data["file_format"] = data.pop("format")
        except KeyError:
            pass
        return data

backend/covid_report/polling/api/views.py
from datetime import datetime
from django.db.models import QuerySet
from rest_framework.generics import RetrieveUpdateAPIView
from rest_framework.viewsets import ModelViewSet
from backend.auth.mixins import OrganizationRequiredMixin
from backend.auth.mixins import ReporterRequiredMixin
from backend.covid_report.polling.api.serializers import DatapointSerializer, DatapointsSerializer
from backend.covid_report.polling.models import Datapoint


class DatapointUpdateApiView(
    RetrieveUpdateAPIView,
    ReporterRequiredMixin,
    OrganizationRequiredMixin,
):
    model = Datapoint
    serializer_class = DatapointSerializer

    def get_queryset(self) -> QuerySet:
        return Datapoint.objects.filter(
            organization__in=self.request.user.get_accessible_organizations(),
        )



class DatapointsViewSet(ModelViewSet,ReporterRequiredMixin,OrganizationRequiredMixin):
    """
    Endpoint to pull list of Answers. Query is limited to organization accessible by user.

    Parameters:

        organization (ex: abc-wehr): filter by slug of an organization

        timeslot (ex: 05-02-2022): from when to build report

        question (ex: how%20is%20it%3F): url encoded question 

    """
    model = Datapoint
    serializer_class = DatapointsSerializer

    def get_queryset(self) -> QuerySet:
        filters = {
            'organization__in':self.request.user.get_accessible_organizations()
        }

        if 'organization' in self.request.GET:
            filters['organization__slug'] = self.request.GET['organization']

        if 'timeslot' in self.request.GET:
            filters['timeslot__deadline__gte'] = datetime.strptime(self.request.GET['timeslot'], '%d-%m-%Y')

        if 'question' in self.request.GET:
            filters['timeslot__metric__question'] =  self.request.GET['question']

        return Datapoint.objects.filter(**filters)

backend/covid_report/polling/views.py
import datetime
from typing import List
from typing import Optional

import attr
import pytz
from basicauth.decorators import basic_auth_required
from dateutil import parser
from django.conf import settings
from django.contrib import messages
from django.db.models import Q
from django.db.models import QuerySet
from django.http import HttpRequest
from django.http import HttpResponse
from django.http import HttpResponseBadRequest
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.functional import cached_property
from django.utils.translation import pgettext
from django.views import View
from django.views.generic import ListView
from django.views.generic import TemplateView
from import_export.mixins import ExportViewFormMixin

from backend.auth.mixins import OrganizationAccessMixin
from backend.auth.mixins import OrganizationRequiredMixin
from backend.auth.mixins import ReporterRequiredMixin
from backend.auth.mixins import ViewerRequiredMixin
from backend.auth.mixins import login_required_error
from backend.auth.models import Organization
from backend.covid_report.polling import forms
from backend.covid_report.polling import models
from backend.covid_report.polling import utils
from backend.covid_report.polling.import_export.datapoint import (
    DatapointResource,
)
from backend.covid_report.polling.middleware import Redirect
from backend.covid_report.polling.models import Datapoint
from backend.covid_report.polling.models import Metric


def homepage(request: HttpRequest) -> HttpResponseRedirect:
    if request.user.is_anonymous:
        raise Redirect("account_login", login_required_error)
    elif request.user.is_can_report:
        return redirect("polling:pending")
    elif request.user.is_can_view:
        return redirect("polling:submitted-metric-list")
    elif request.user.is_superuser or request.user.is_staff:
        return redirect("polling:pending")
    elif request.user.is_reviewer:
        return redirect('admin:index')
    else:
        messages.error(
            request,
            pgettext(
                "auth", "You are not allowed to access the reports pages.",
            ),
        )
        return redirect(settings.LOGIN_URL)


@attr.s
class OrganizationMetric:
    organization: models.Organization = attr.ib()
    metric: models.Metric = attr.ib()
    _timestamp: datetime.datetime = attr.ib(factory=timezone.now)

    def datapoints(self):
        return models.Datapoint.objects.filter(
            organization=self.organization, timeslot__metric=self.metric
        )

    @cached_property
    def past_datapoints(self):
        return self.datapoints().before(self._timestamp)

    @cached_property
    def future_datapoints(self) -> QuerySet:
        return self.datapoints().after(self._timestamp)

    @cached_property
    def overdue_datapoints(self):
        qs = self.past_datapoints.unsubmitted()
        return list(
            qs.optional(
                self.metric,
                self.past_datapoints.last_optional(self.metric)
            )
        ) + list(
            qs.compulsory()
        )

    @cached_property
    def last_entry(self):
        return self.past_datapoints.submitted().last()

    @cached_property
    def next_datapoint(self) -> Optional[Datapoint]:
        return self.future_datapoints.first()

    def to_fill(self) -> List[Datapoint]:
        if self.metric.is_optional:
            if self.next_datapoint:
                return [self.next_datapoint]
        else:
            if self.next_datapoint:
                return self.overdue_datapoints + [self.next_datapoint]
            else:
                return self.overdue_datapoints


class ReporterRedirectView(ReporterRequiredMixin, OrganizationRequiredMixin, View):
    def get(self, request: HttpRequest) -> HttpResponse:
        return redirect(
            'polling:pending_for_org',
            org_slug=request.user.get_accessible_organizations().first().slug,
        )


class ReporterIndexView(
    ReporterRequiredMixin, OrganizationRequiredMixin, OrganizationAccessMixin, TemplateView
):
    template_name = "polling/pending_datapoints.html"

    def get_context_data(self, **kwargs):
        org_current = Organization.objects.get(slug=kwargs.get('org_slug'))
        now = timezone.now()
        metric_ids = (
            models.Datapoint.objects
                .filter(
                Q(submission_datetime__isnull=True, timeslot__deadline__lt=now)
                | Q(timeslot__deadline__gte=now)
            )
                .filter(organization=org_current)
                .values_list("timeslot__metric_id", flat=True)
                .distinct()
        )
        metrics = models.Metric.objects.filter(pk__in=metric_ids)
        return {
            **super().get_context_data(**kwargs),
            "org_current": org_current,
            "org_list": self.request.user.get_accessible_organizations(),
            "metrics": [
                OrganizationMetric(org_current, m, now) for m in metrics
            ],
        }


class SubmittedMetricListView(
    ViewerRequiredMixin, OrganizationRequiredMixin, OrganizationAccessMixin, ListView
):
    model = models.Metric
    template_name = "polling/submitted_metric_list.html"

    def get_context_data(self, **kwargs):
        organization = self.request.user.organization
        now = timezone.now()

        metric_ids = (
            models.Datapoint.objects.submitted()
                .filter(organization=organization)
                .values_list("timeslot__metric_id", flat=True)
                .distinct()
        )
        metrics = models.Metric.objects.filter(pk__in=metric_ids)
        return {
            **super().get_context_data(**kwargs),
            "metrics": [
                OrganizationMetric(organization, m, now) for m in metrics
            ],
        }


class MetricHistoryView(
    ViewerRequiredMixin, OrganizationRequiredMixin, OrganizationAccessMixin, TemplateView,
):
    template_name = "polling/metric_history.html"

    def get_context_data(self, **kwargs):
        self.object = Metric.objects.get(pk=kwargs['pk'])
        org_current = Organization.objects.get(slug=kwargs.get('org_slug'))
        return {
            "org_current": org_current,
            "org_metric": OrganizationMetric(org_current, self.object),
            "org_list": self.request.user.get_accessible_organizations().order_by('name'),
            "object": self.object,
        }


@method_decorator(basic_auth_required, name='dispatch')
class ExportView(ExportViewFormMixin, ListView):
    model = models.Datapoint
    resource_class = DatapointResource
    form_class = forms.ExportForm

    def get_queryset(self) -> List[Datapoint]:
        queryset: QuerySet = (
            super().get_queryset()
                .submitted()
                .select_related(
                'organization',
                'timeslot__metric',
                'timeslot__metric__polling_frequency',
                'timeslot',
                'submitting_user',
            )
                .prefetch_related(
                'organization__types',
            )
        )
        date_start = self.get_date_start()
        # max_days = self.get_max_days()
        max_days = None

        if date_start:
            date_start = date_start

            if max_days:
                end_date = date_start + datetime.timedelta(days=int(max_days) - 1, hours=23, minutes=59, seconds=59)
                end_date = end_date
                queryset = queryset.filter(submission_datetime__gte=date_start, submission_datetime__lte=end_date)

            else:
                queryset = queryset.filter(submission_datetime__gte=date_start)

        # there's a bug in iterator that bypasses prefetch_related
        # that's why we iterate here instead
        # perhaps related to django-import-export#774
        return [instance for instance in queryset]

    def get_form_kwargs(self):
        return {
            'initial': self.get_initial(),
            'data': self.request.GET,
            'formats': self.get_export_formats(),
        }

    def form_invalid(self, form):
        return HttpResponseBadRequest()

    def get(self, request, *args, **kwargs):
        utils.copy_last_value_if_slot_was_missed()

        self.object_list = self.get_queryset()
        return super().post(request, *args, **kwargs)

    def get_date_start(self) -> Optional[datetime.datetime]:
        start_date_raw: str = self.request.GET.get('start_date', None)
        if start_date_raw:
            return parser.parse(start_date_raw)
        else:
            return None

    def get_max_days(self) -> Optional[int]:
        return self.request.GET.get('max_days', None)

backend/covid_report/polling/templates/polling/metric_history.html
{% extends "base.html" %}

{% load i18n tz %}

{% block page_meta_title %}{% trans "Past Answers" %}{% endblock %}

{% get_current_timezone as TIME_ZONE %}

{% block content %}
    <div class="mb-4">
        <a href="{% url "polling:pending_for_org" org_slug=org_current.slug %}" id="back-link">&#8249; {% trans "Back" %}</a>
    </div>

    {% include "polling/includes/metric_history_table.html" %}

    <p class="small text-secondary">
        {% blocktrans trimmed with timezone=TIME_ZONE %}All times shown in <code>{{ timezone }}</code> timezone.{% endblocktrans %}
    </p>
{% endblock %}

backend/covid_report/polling/templates/polling/pending_datapoints.html
{% extends "base.html" %}

{% load i18n %}

{% block page_meta_title %}{% trans "Pending Reports" %}{% endblock %}

{% block content %}
    <div class="col-md-20 offset-md-2">
        {% if not metrics %}
            <div class="alert alert-info" role="alert">
                {% trans "You don't have any pending reports." %}
            </div>
        {% endif %}

        {% for org_metric in metrics %}
            {% with has_status=org_metric.metric.has_status has_number=org_metric.metric.has_number has_text=org_metric.metric.has_text %}
                <div class="card slot-container mb-4">
                    <div class="card-header">
                        <strong>{{ org_metric.metric.question }}</strong>
                    </div>
                    {% if org_metric.metric.help_text %}
                        <div class="card-body border-bottom">
                            {{ org_metric.metric.help_text|linebreaksbr }}
                        </div>
                    {% endif %}
                    <div class="card-body p-0">
                        <div class="row grid-divider">
                            {% with datapoint=org_metric.last_entry %}
                                <div class="col-md-6 order-md-first order-last text-center p-4">
                                    <p class="mb-1"><strong>{% trans "Last entry" %}</strong></p>
                                    <p class="small" >
                                        {% trans "Not yet submitted" as default %}
                                        {{ datapoint.timeslot.deadline|date:"d.m.Y H:i"|default:default }}
                                    </p>
                                    {% if datapoint.is_type_numeric %}
                                        <h4 class="h1 text-secondary slot-number">
                                            {% if datapoint.is_submitted %}
                                                {{ datapoint.numeric_value }}
                                            {% else %}
                                                –
                                            {% endif %}
                                        </h4>
                                    {% endif %}
                                    {% if datapoint.is_type_status %}
                                        <h4>
                                            <span class="badge badge-pill badge-{{ datapoint.get_status_value_class|default:"light border border-secondary" }}" style="width: 100px;">
                                                {% if datapoint.is_submitted %}
                                                    <span class="small">{{ datapoint.get_status_value_display }}</span>
                                                {% else %}
                                                    &mdash;
                                                {% endif %}
                                            </span>
                                        </h4>
                                    {% endif %}
                                    <div class="pt-3">
                                        <a class="small" href="{% url "polling:metric-history" org_slug=org_current.slug pk=org_metric.metric.pk %}">{% trans "All entries" %}</a>
                                    </div>
                                </div>
                            {% endwith %}
                            <div class="col-md-18 slot-details">
                                {% for datapoint in org_metric.to_fill %}
                                    {% with form=datapoint.get_form is_bound=form.value.initial %}
                                        {% if form.is_filled %}

                                        {% endif %}
                                        <form
                                            id="form-{{datapoint.pk}}"
                                            action="{% url "polling:json-submit" pk=datapoint.pk %}"
                                            method="post"
                                            class="slot slot-form"
                                            data-time="{{ datapoint.timeslot.deadline|date:"d.m.Y H:i" }}"
                                            data-is-filled="{{ form.is_filled|lower }}"
                                            data-name="{{ org_metric.metric.question }}"
                                            data-is-text="{{ datapoint.is_text|lower }}"
                                        >
                                            {% csrf_token %}
                                            <div class="">
                                                <p class="pb-0 mb-0{% if datapoint.is_overdue and not datapoint.is_optional %} text-danger{% endif %}">
                                                    <strong>
                                                        {% blocktrans trimmed with deadline=datapoint.timeslot.deadline|date:"d.m.Y, H:i" %}
                                                            Answer for {{ deadline }}
                                                        {% endblocktrans %}
                                                    </strong>
                                                </p>
                                                <p class="small text-secondary">{{ org_metric.metric.polling_frequency.name }}</p>
                                            </div>

                                            <div class="form-inline">
                                                {% if has_status or has_number %}
                                                    {% if has_status %}
                                                        {% include 'forms/field.html' with field=form.value form=form %}
                                                    {% endif %}

                                                    {% if has_number %}
                                                        {% include 'forms/field.html' with field=form.value form=form %}
                                                    {% endif %}
                                                {% elif has_text  %}
                                                    {% include 'forms/field.html' with field=form.value form=form %}
                                                {% endif %}

                                                <button id="confirm-submit-{{ datapoint.pk }}"
                                                        class="btn form-submit-btn btn-primary mt-2 ml-md-2 ml-sm-0 mt-md-0 mr-sm-2"
                                                        type="button"
                                                >
                                                {% trans "Save" %}
                                                </button>

                                                <span 
                                                    class="mr-sm-2 ml-2 edit-btn"
                                                    data-is-visible="{{ form.is_filled|lower }}"
                                                >
                                                    {% include 'polling/includes/edit-icon.svg' %}{% trans "Edit" context 'question' %}
                                                </span>
                                            </div>
                                            {% if has_status or has_number %}
                                                {% if has_text and org_metric.metric.is_enable_comment %}
                                                    <div class="form-group mb-1 mt-2">
                                                        <label class="form-check-label">
                                                            <input id="{{ datapoint.pk }}"
                                                                   class="form-check comment-checkbox form-check-inline"
                                                                   type="checkbox"
                                                            >{% trans "Comment" %}
                                                        </label>
                                                    </div>
                                                    <div class="form-group mb-2 comment-input-container none" id="comment-input-container-{{datapoint.pk}}">
                                                        {% include 'forms/field.html' with field=form.comment form=form %}
                                                    </div>
                                                {% endif %}
                                            {% endif %}
                                        
                                            <div class="error"></div>

                                        </form>
                                    {% endwith %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endwith %}
        {% endfor %}


    </div>

    <!-- Modal -->
    <div class="modal fade" id="datapoint-confirmation-modal" tabindex="-1" role="dialog"
         aria-labelledby="confirm-submit"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header container">
                    <h5 class="modal-title" id="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body container">
                    <p>
                        {% trans "Please confirm the following" %}
                    </p>
                    <div class="alert alert-primary" role="alert">
                        <p><strong>{% trans "Date" %}:&nbsp</strong><span id="time_text"></span></p>
                        <p id="value-section"><strong>{% trans "Value" %}:&nbsp</strong><span id="value_text"></span></p>
                        <p id="comment-section"><strong>{% trans "Comment" %}:&nbsp</strong><span id="comment_text"></span></p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" id="modal-submit" class="btn btn-primary">{% trans "Confirm" %}</button>
                    <button type="button" class="btn btn-outline-primary" data-dismiss="modal">{% trans "Cancel" %}</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

backend/covid_report/polling/templates/polling/submitted_metric_list.html
{% extends "base.html" %}

{% load i18n tz %}

{% block page_meta_title %}{% trans "Past Reports" %}{% endblock %}

{% get_current_timezone as TIME_ZONE %}

{% block content %}
    {% for org_metric in metrics %}
        {% include "polling/includes/metric_history_table.html" %}
    {% endfor %}

    <p class="small text-secondary">
        {% blocktrans trimmed with timezone=TIME_ZONE %}
            All times shown in <code>{{ timezone }}</code> timezone.
        {% endblocktrans %}
    </p>
{% endblock %}